const megaDB = [
  // هنا تضع كل العناصر
];
{ n: "The Godfather", t: "فيلم", img: "https://...", link: "https://..." },
{ n: "Naruto", t: "أنمي", img: "https://...", link: "https://..." },
{ n: "Toyota Supra", t: "سيارة", img: "https://...", link: "https://..." },
const megaDB = [  { n: "The Godfather", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", link: "https://www.imdb.com/title/tt0068646/" },
  { n: "The Dark Knight", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMDk2Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0468569/" },
  { n: "Inception", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt1375666/" },
  { n: "Interstellar", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0816692/" },
  { n: "Fight Club", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMmEzNTYxZTUtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0137523/" }
  // ... تكمل بنفس النمط حتى تصل إلى 200 فيلم
];const megaDB = [  { n: "The Godfather", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", link: "https://www.imdb.com/title/tt0068646/" },
  { n: "The Dark Knight", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMDk2Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0468569/" },
  { n: "Inception", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt1375666/" },
  { n: "Interstellar", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0816692/" },
  { n: "Fight Club", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMmEzNTYxZTUtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0137523/" },
  { n: "Pulp Fiction", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0110912/" },
  { n: "Forrest Gump", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNWIwODkzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0109830/" },
  { n: "The Matrix", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3NzAtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0133093/" },
  { n: "Se7en", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0114369/" },
  { n: "Gladiator", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0172495/" },
  { n: "The Shawshank Redemption", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0111161/" },
  { n: "The Silence of the Lambs", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0102926/" },
  { n: "Saving Private Ryan", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120815/" },
  { n: "Schindler's List", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0108052/" },
  { n: "The Lord of the Rings: The Fellowship of the Ring", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120737/" },
  { n: "The Lord of the Rings: The Two Towers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167261/" },
  { n: "The Lord of the Rings: The Return of the King", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167260/" },
  { n: "The Avengers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0848228/" },
  { n: "Iron Man", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0371746/" },
  { n: "Avatar", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0499549/" }
];const megaDB = [ { n: "Goodfellas", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0099685/" },
  { n: "The Departed", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0407887/" },
  { n: "Whiplash", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt2582802/" },
  { n: "The Prestige", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0482571/" },
  { n: "Memento", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0209144/" },
  { n: "Django Unchained", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt1853728/" },
  { n: "The Wolf of Wall Street", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0993846/" },
  { n: "Shutter Island", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt1130884/" },
  { n: "The Social Network", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt1285016/" },
  { n: "Parasite", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt6751668/" },
  { n: "Joker", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt7286456/" },
  { n: "Mad Max: Fury Road", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt1392190/" },
  { n: "The Revenant", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt1663202/" },
  { n: "Birdman", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt2562232/" },
  { n: "La La Land", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt3783958/" },
  { n: "Titanic", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120338/" },
  { n: "Casablanca", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0034583/" },
  { n: "City of God", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0317248/" },
  { n: "American Beauty", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0169547/" },
  { n: "The Green Mile", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120689/" }
];const megaDB = [
  { n: "The Pianist", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0253474/" },
  { n: "Amélie", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0211915/" },
  { n: "Requiem for a Dream", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0180093/" },
  { n: "Eternal Sunshine of the Spotless Mind", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0338013/" },
  { n: "The Truman Show", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120382/" },
  { n: "The Sixth Sense", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167404/" },
  { n: "A Beautiful Mind", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0268978/" },
  { n: "Black Swan", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0947798/" },
  { n: "The Grand Budapest Hotel", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt2278388/" },
  { n: "Moonlight", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt4975722/" },
  { n: "12 Years a Slave", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt2024544/" },
  { n: "The Big Lebowski", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0118715/" },
  { n: "No Country for Old Men", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0477348/" },
  { n: "There Will Be Blood", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0469494/" },
  { n: "The Usual Suspects", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0114814/" },
  { n: "Reservoir Dogs", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0105236/" },
  { n: "The Hunt", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt2106476/" },
  { n: "Oldboy", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0364569/" },
  { n: "Pan's Labyrinth", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0457430/" }
];const megaDB = [
  { n: "The Godfather", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", link: "https://www.imdb.com/title/tt0068646/" },
  { n: "The Dark Knight", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMDk2Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0468569/" },
  { n: "Inception", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt1375666/" },
  { n: "Interstellar", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0816692/" },
  { n: "Fight Club", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMmEzNTYxZTUtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0137523/" },
  { n: "Pulp Fiction", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0110912/" },
  { n: "Forrest Gump", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNWIwODkzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0109830/" },
  { n: "The Matrix", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3NzAtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0133093/" },
  { n: "Se7en", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0114369/" },
  { n: "Gladiator", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0172495/" },
  { n: "The Shawshank Redemption", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0111161/" },
  { n: "The Silence of the Lambs", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0102926/" },
  { n: "Saving Private Ryan", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120815/" },
  { n: "Schindler's List", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0108052/" },
  { n: "The Lord of the Rings: The Fellowship of the Ring", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120737/" },
  { n: "The Lord of the Rings: The Two Towers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167261/" },
  { n: "The Lord of the Rings: The Return of the King", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167260/" },
  { n: "The Avengers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0848228/" },
  { n: "Iron Man", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0371746/" },
];const megaDB = [
  { n: "The Godfather", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", link: "https://www.imdb.com/title/tt0068646/" },
  { n: "The Dark Knight", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMDk2Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0468569/" },
  { n: "Inception", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt1375666/" },
  { n: "Interstellar", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0816692/" },
  { n: "Fight Club", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMmEzNTYxZTUtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0137523/" },
  { n: "Pulp Fiction", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0110912/" },
  { n: "Forrest Gump", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNWIwODkzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0109830/" },
  { n: "The Matrix", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3NzAtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0133093/" },
  { n: "Se7en", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0114369/" },
  { n: "Gladiator", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0172495/" },
  { n: "The Shawshank Redemption", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0111161/" },
  { n: "The Silence of the Lambs", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0102926/" },
  { n: "Saving Private Ryan", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120815/" },
  { n: "Schindler's List", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0108052/" },
  { n: "The Lord of the Rings: The Fellowship of the Ring", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120737/" },
  { n: "The Lord of the Rings: The Two Towers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167261/" },
  { n: "The Lord of the Rings: The Return of the King", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167260/" },
  { n: "The Avengers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0848228/" },
  { n: "Iron Man", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0371746/" },
  ];const megaDB = [
  { n: "The Godfather", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", link: "https://www.imdb.com/title/tt0068646/" },
  { n: "The Dark Knight", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMDk2Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0468569/" },
  { n: "Inception", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt1375666/" },
  { n: "Interstellar", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0816692/" },
  { n: "Fight Club", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMmEzNTYxZTUtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0137523/" },
  { n: "Pulp Fiction", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0110912/" },
  { n: "Forrest Gump", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNWIwODkzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0109830/" },
  { n: "The Matrix", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3NzAtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0133093/" },
  { n: "Se7en", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0114369/" },
  { n: "Gladiator", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0172495/" },
  { n: "The Shawshank Redemption", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0111161/" },
  { n: "The Silence of the Lambs", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0102926/" },
  { n: "Saving Private Ryan", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120815/" },
  { n: "Schindler's List", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0108052/" },
  { n: "The Lord of the Rings: The Fellowship of the Ring", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120737/" },
  { n: "The Lord of the Rings: The Two Towers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167261/" },
  { n: "The Lord of the Rings: The Return of the King", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167260/" },
  { n: "The Avengers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0848228/" },
  { n: "Iron Man", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0371746/" },
  ];const megaDB = [
  { n: "The Godfather", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", link: "https://www.imdb.com/title/tt0068646/" },
  { n: "The Dark Knight", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMDk2Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0468569/" },
  { n: "Inception", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt1375666/" },
  { n: "Interstellar", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0816692/" },
  { n: "Fight Club", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMmEzNTYxZTUtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0137523/" },
  { n: "Pulp Fiction", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0110912/" },
  { n: "Forrest Gump", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNWIwODkzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0109830/" },
  { n: "The Matrix", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3NzAtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0133093/" },
  { n: "Se7en", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0114369/" },
  { n: "Gladiator", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0172495/" },
  { n: "The Shawshank Redemption", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0111161/" },
  { n: "The Silence of the Lambs", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0102926/" },
  { n: "Saving Private Ryan", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120815/" },
  { n: "Schindler's List", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0108052/" },
  { n: "The Lord of the Rings: The Fellowship of the Ring", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120737/" },
  { n: "The Lord of the Rings: The Two Towers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167261/" },
  { n: "The Lord of the Rings: The Return of the King", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167260/" },
  { n: "The Avengers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0848228/" },
  { n: "Iron Man", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0371746/" },
  ];const megaDB = [
  { n: "The Godfather", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg", link: "https://www.imdb.com/title/tt0068646/" },
  { n: "The Dark Knight", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMDk2Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0468569/" },
  { n: "Inception", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt1375666/" },
  { n: "Interstellar", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0816692/" },
  { n: "Fight Club", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMmEzNTYxZTUtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0137523/" },
  { n: "Pulp Fiction", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNGNhMDIzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0110912/" },
  { n: "Forrest Gump", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNWIwODkzY2UtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0109830/" },
  { n: "The Matrix", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BNzQzOTk3NzAtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0133093/" },
  { n: "Se7en", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0114369/" },
  { n: "Gladiator", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0172495/" },
  { n: "The Shawshank Redemption", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtYzYxZS00ZjQ5LTg5ZTUtYjYzYzYzYzYzYzYzXkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_.jpg", link: "https://www.imdb.com/title/tt0111161/" },
  { n: "The Silence of the Lambs", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0102926/" },
  { n: "Saving Private Ryan", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120815/" },
  { n: "Schindler's List", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0108052/" },
  { n: "The Lord of the Rings: The Fellowship of the Ring", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0120737/" },
  { n: "The Lord of the Rings: The Two Towers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167261/" },
  { n: "The Lord of the Rings: The Return of the King", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0167260/" },
  { n: "The Avengers", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0848228/" },
  { n: "Iron Man", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt0371746/" },
  { n: "The Departed", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt0407887/" },
  { n: "Whiplash", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNzM0MF5BMl5BanBnXkFtZTgwNjUxNzE3MjE@._V1_.jpg", link: "https://www.imdb.com/title/tt2582802/" },
  { n: "The Prestige", t: "فيلم", img: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg", link: "https://www.imdb.com/title/tt
    const megaDB = [
  { n: "The Godfather", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0068646/" },
  { n: "The Dark Knight", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0468569/" },
  { n: "Inception", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt1375666/" },
  { n: "Interstellar", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0816692/" },
  { n: "Fight Club", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0137523/" },
  { n: "Pulp Fiction", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0110912/" },
  { n: "Forrest Gump", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0109830/" },
  { n: "The Matrix", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0133093/" },
  { n: "Se7en", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0114369/" },
  { n: "Gladiator", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0172495/" },
  { n: "The Shawshank Redemption", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0111161/" },
  { n: "The Silence of the Lambs", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0102926/" },
  { n: "Saving Private Ryan", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0120815/" },
  { n: "Schindler's List", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0108052/" },
  { n: "The Lord of the Rings: The Fellowship of the Ring", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0120737/" },
  { n: "The Lord of the Rings: The Two Towers", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0167261/" },
  { n: "The Lord of the Rings: The Return of the King", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0167260/" },
  { n: "The Avengers", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0848228/" },
  { n: "Iron Man", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0371746/" },
  { n: "The Departed", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0407887/" },
  { n: "Whiplash", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt2582802/" },
  { n: "The Prestige", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0482571/" },
  { n: "Memento", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0209144/" },
  { n: "Django Unchained", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt1853728/" },
  { n: "The Wolf of Wall Street", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0993846/" },
  { n: "Shutter Island", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt1130884/" },
  { n: "The Social Network", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt1285016/" },
  { n: "Parasite", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt6751668/" },
  { n: "Joker", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt7286456/" },
  { n: "Mad Max: Fury Road", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt1392190/" },
  { n: "The Revenant", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt1663202/" },
  { n: "Birdman", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt2562232/" },
  { n: "La La Land", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt3783958/" },
  { n: "Titanic", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0120338/" },
  { n: "Casablanca", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0034583/" },
  { n: "City of God", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0317248/" },
  { n: "American Beauty", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0169547/" },
  { n: "The Green Mile", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0120689/" },
  { n: "The Pianist", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0253474/" },
  { n: "Amélie", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0211915/" },
  { n: "Requiem for a Dream", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0180093/" },
  { n: "Eternal Sunshine of the Spotless Mind", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0338013/" },
  { n: "The Truman Show", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0120382/" },
  { n: "The Sixth Sense", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0167404/" },
  { n: "A Beautiful Mind", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0268978/" },
  { n: "Black Swan", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0947798/" },
  { n: "The Grand Budapest Hotel", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt2278388/" },
  { n: "Moonlight", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt4975722/" },
  { n: "12 Years a Slave", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt2024544/" },
  { n: "The Big Lebowski", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0118715/" },
  { n: "No Country for Old Men", t: "فيلم", img: "https://...", link: "https://www.imdb.com/title/tt0477348/" },
  { n: "There
    const megaDB = [
  { n: "Naruto", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/13/17405.jpg", link: "https://myanimelist.net/anime/20/Naruto" },
  { n: "Naruto: Shippuden", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/5/17407.jpg", link: "https://myanimelist.net/anime/1735/Naruto__Shippuuden" },
  { n: "Attack on Titan", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/10/47347.jpg", link: "https://myanimelist.net/anime/16498/Shingeki_no_Kyojin" },
  { n: "Death Note", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/9/9453.jpg", link: "https://myanimelist.net/anime/1535/Death_Note" },
  { n: "One Piece", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/6/73245.jpg", link: "https://myanimelist.net/anime/21/One_Piece" },
  { n: "Dragon Ball Z", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/7/73940.jpg", link: "https://myanimelist.net/anime/813/Dragon_Ball_Z" },
  { n: "Dragon Ball Super", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/7/74606.jpg", link: "https://myanimelist.net/anime/30694/Dragon_Ball_Super" },
  { n: "Bleach", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/3/40451.jpg", link: "https://myanimelist.net/anime/269/Bleach" },
  { n: "Fullmetal Alchemist: Brotherhood", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/1223/96541.jpg", link: "https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood" },
  { n: "Hunter x Hunter", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/11/33657.jpg", link: "https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011" },
  { n: "Tokyo Ghoul", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/5/64449.jpg", link: "https://myanimelist.net/anime/22319/Tokyo_Ghoul" },
  { n: "Demon Slayer: Kimetsu no Yaiba", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg", link: "https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba" },
  { n: "Jujutsu Kaisen", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg", link: "https://myanimelist.net/anime/40748/Jujutsu_Kaisen" },
  { n: "My Hero Academia", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/10/78745.jpg", link: "https://myanimelist.net/anime/31964/Boku_no_Hero_Academia" },
  { n: "Sword Art Online", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/11/39717.jpg", link: "https://myanimelist.net/anime/11757/Sword_Art_Online" },
  { n: "Black Clover", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/2/88336.jpg", link: "https://myanimelist.net/anime/34572/Black_Clover" },
  { n: "Fairy Tail", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/5/18179.jpg", link: "https://myanimelist.net/anime/6702/Fairy_Tail" },
  { n: "Code Geass", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/5/50331.jpg", link: "https://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch" },
  { n: "One Punch Man", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/12/76049.jpg", link: "https://myanimelist.net/anime/30276/One_Punch_Man" },
  { n: "Chainsaw Man", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg", link: "https://myanimelist.net/anime/44511/Chainsaw_Man" }
];const megaDB = [
  { n: "Naruto", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/13/17405.jpg", link: "https://myanimelist.net/anime/20/Naruto" },
  { n: "Naruto: Shippuden", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/5/17407.jpg", link: "https://myanimelist.net/anime/1735/Naruto__Shippuuden" },
  { n: "Attack on Titan", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/10/47347.jpg", link: "https://myanimelist.net/anime/16498/Shingeki_no_Kyojin" },
  { n: "Death Note", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/9/9453.jpg", link: "https://myanimelist.net/anime/1535/Death_Note" },
  { n: "One Piece", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/6/73245.jpg", link: "https://myanimelist.net/anime/21/One_Piece" },
  { n: "Dragon Ball Z", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/7/73940.jpg", link: "https://myanimelist.net/anime/813/Dragon_Ball_Z" },
  { n: "Dragon Ball Super", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/7/74606.jpg", link: "https://myanimelist.net/anime/30694/Dragon_Ball_Super" },
  { n: "Bleach", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/3/40451.jpg", link: "https://myanimelist.net/anime/269/Bleach" },
  { n: "Fullmetal Alchemist: Brotherhood", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/1223/96541.jpg", link: "https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood" },
  { n: "Hunter x Hunter", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/11/33657.jpg", link: "https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011" },
  { n: "Tokyo Ghoul", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/5/64449.jpg", link: "https://myanimelist.net/anime/22319/Tokyo_Ghoul" },
  { n: "Demon Slayer: Kimetsu no Yaiba", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/1286/99889.jpg", link: "https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba" },
  { n: "Jujutsu Kaisen", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/1171/109222.jpg", link: "https://myanimelist.net/anime/40748/Jujutsu_Kaisen" },
  { n: "My Hero Academia", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/10/78745.jpg", link: "https://myanimelist.net/anime/31964/Boku_no_Hero_Academia" },
  { n: "Sword Art Online", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/11/39717.jpg", link: "https://myanimelist.net/anime/11757/Sword_Art_Online" },
  { n: "Black Clover", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/2/88336.jpg", link: "https://myanimelist.net/anime/34572/Black_Clover" },
  { n: "Fairy Tail", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/5/18179.jpg", link: "https://myanimelist.net/anime/6702/Fairy_Tail" },
  { n: "Code Geass", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/5/50331.jpg", link: "https://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch" },
  { n: "One Punch Man", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/12/76049.jpg", link: "https://myanimelist.net/anime/30276/One_Punch_Man" },
  { n: "Chainsaw Man", t: "أنمي", img: "https://cdn.myanimelist.net/images/anime/1806/126216.jpg", link: "https://myanimelist.net/anime/44511/Chainsaw_Man" },
  ];
    { n: "اسم الأنمي", t: "أنمي", img: "رابط صورة", link: "رابط خارجي" }

